# Generated by Django 4.1.2 on 2023-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KategoriModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategori", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "kategoriler",
            },
        ),
        migrations.CreateModel(
            name="EmpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=150)),
                ("agirlik", models.CharField(max_length=150)),
                ("fiyat", models.CharField(max_length=150)),
                ("kategori", models.ManyToManyField(to="CRUDOperation.kategorimodel")),
            ],
            options={
                "db_table": "iha",
            },
        ),
    ]
