# Generated by Django 4.1.2 on 2023-02-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUDOperation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empmodel",
            name="fiyat",
        ),
    ]
