# Generated by Django 4.1.2 on 2023-02-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUDOperation", "0002_remove_empmodel_fiyat"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="kategorimodel",
            table="kategori",
        ),
    ]
