# Generated by Django 4.1.2 on 2023-02-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUDOperation", "0004_rename_kategori_empmodel_kategori_pk"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmpModel",
            new_name="IhaModel",
        ),
    ]
