# Generated by Django 4.1.2 on 2023-02-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CRUDOperation", "0005_rename_empmodel_ihamodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ihamodel",
            name="kategori_pk",
        ),
        migrations.AddField(
            model_name="ihamodel",
            name="kategori",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CRUDOperation.kategorimodel",
            ),
        ),
    ]
