# Generated by Django 4.1.2 on 2023-02-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUDOperation", "0006_remove_ihamodel_kategori_pk_ihamodel_kategori"),
    ]

    operations = [
        migrations.CreateModel(
            name="KullaniciModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adi", models.CharField(max_length=150)),
                ("soyadi", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("sifre", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "kullanicilar",
            },
        ),
    ]
